### Send request with dynamic variables in request's body
POST http://localhost:8088/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "user",
  "password": "1111"
}

###

### Send request with dynamic variables in request's body
POST http://localhost:8088/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "manager",
  "password": "1111"
}

###

### Send request with dynamic variables in request's body
GET http://localhost:8088/api/messages
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "manager",
  "password": "1111"
}

###

### Send request with dynamic variables in request's body
GET http://localhost:8088/api/messages
Content-Type: application/json
X-Requested-With: XMLHttpRequest

###